### ISSUE TITLE
I need someone to help with this referencing of USA score 42/100

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#1]
<img width="703" alt="Screen Shot 2020-03-12 at 12 55 08 PM" src="https://user-images.githubusercontent.com/3658863/76561548-c2705080-6460-11ea-9fd8-a35c16a1ad04.png">

**Comment by mandie722** [comment]
Page 303 of this report https://www.ghsindex.org/wp-content/uploads/2019/10/2019-Global-Health-Security-Index.pdf has the United States with an overall index score of 83.5 which places them as first out of 195 countries.  I'm not sure where the 42 comes from.

**Comment by monicacecilia** [comment]
I just saw this response on the SoT google doc:
![Screen Shot 2020-03-12 at 3 14 03 PM](https://user-images.githubusercontent.com/1714621/76571187-251f1780-6474-11ea-9413-0fb994996e5b.png)
I agree with here and I think it solves the issue. 
Tanks, @jmcmurry - you can close.

**Comment by monicacecilia** [comment]
This has been addressed in the Spanish version adding one additional sentence. Based on advice from the user, I added: 

```Their study created a scale of 0-100 points, measuring a country's level of pandemic preparedness.```

I've added this to the 'private' google doc and this could also be added to the new website.

**Comment by jaysonvirissimo** [comment]
This paper is not so easy to find, but here are some clues:
PMID: 21870667
DOI: https://doi.org/10.5055/ajdm.2011.0058

**Comment by jaysonvirissimo** [comment]
I've reached out to several of the authors for the paper and am waiting to hear back... 🤞

**Comment by steesdale** [comment]
Hey @jaysonvirissimo what are you trying to find?  

Not sure if this helps, but: 

The WHO carries out the JEE evaluation - https://www.who.int/ihr/procedures/mission-reports/en/

These are widely thought of as the most current/comprehensive evaluations of readiness. 

Resolve to Save Lives has a helpful website sharing these: https://preventepidemics.org/

**Comment by jaysonvirissimo** [comment]
I'm looking for [this](https://www.ncbi.nlm.nih.gov/pubmed/21870667) paper (not just the abstract), which I suspect is the source of the original "42 out of 100" claim. Those sources are good and relevant, but don't seem (to me) to actually contain the claim referenced on flattenthecurve.com. Does that make sense?

**Comment by jaysonvirissimo** [comment]
One of the authors of that paper gave me the complete copy and it doesn't score the US as "42 out of 100" (although it does mention that "Only 42 percent of respondents felt that their ED was prepared in the event of a pandemic influenza or other disease outbreak"). 

Is it possible the person in the webinar misspoke?

IMO, we should just re-word this section using only claims that can be easily verified by the reader with links to the primary sources. I can make an attempt at it tonight sometime, if no one else gets to it first.

**Comment by steesdale** [comment]
Agreed - can we also mention the JEE scores and the dates that they were generated?  the 42 percent article is from a decade ago as well.
