### ISSUE TITLE
Images details are not hidden

### ISSUE THREAD

**Issue by mmuller** [flattenthecurve/guide#10]
![image (22)](https://user-images.githubusercontent.com/518152/76650020-8dd3c600-6540-11ea-9741-0bd8b5874a32.png)

![image (23)](https://user-images.githubusercontent.com/518152/76650056-988e5b00-6540-11ea-929c-55d0a7927fbe.png)

**Comment by danimiba** [comment]
Julie's picture visible code appears to be solved in 74a140050a3df835bb21b087408839bafbde43ed

**Comment by waj** [comment]
Fixed in 19dca3602507ad49de906189de90196a46706cb1
