### ISSUE TITLE
Apply text styles

### ISSUE THREAD

**Issue by jkicillof** [flattenthecurve/guide#104]
![image](https://user-images.githubusercontent.com/5031636/76779987-09c14e80-678b-11ea-971a-8b2a37e44ade.png)
Every subtitle, do's and dont's should have at least 1 line height of margin on top

**Comment by chousmith** [comment]
+1 for this one. Was looking if anyone else had taken on overall font. Standard body font of Lato with font-weight: 300 is really light. Font-weight 400 + Roboto would be nicer

**Comment by emersonthis** [comment]
Uh oh. The light blue link style is not WCAG AA compliant for contrast. The darker blue is borderline... it passes the contrast standards at a larger size.

**Comment by emersonthis** [comment]
@danimiba Sorry I didn't noticed that someone assigned this to you! I was directed to this via Slack earlier today, and I didn't double-check the assignment again before making my PR.
cc @nditada

**Comment by danimiba** [comment]
@emersonthis don't worry, I assigned it myself because I was talking to @jkicillof. Please feel free to continue it, as your remarks about a11y are really useful. There are some more style issues we will create tomorrow, it's really late where we are. Thank you very much in advance!
