### ISSUE TITLE
Add CD2H logo (and others) to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [flattenthecurve/guide#116]
Please report the issue under the apppriate header below.

**Content to be added or changed:**
add CD2H logo to website

**Comment by nicolevasilevsky** [comment]
![CD2H_logo_color stacked](https://user-images.githubusercontent.com/6722114/76796278-535c6a00-6788-11ea-98e8-99b5f1e9bd90.png)

**Comment by nicolevasilevsky** [comment]
@mellybelly need clarity as to where this should go (at bottom of the page?) and should this include a funding statement?

**Comment by mellybelly** [comment]
It needs a funding statement as well, yes please. I think it could go in multiple places - potentially at the footer and in the contributors/attributions? depends on layout. 

Here is the funding information and we can link to the CD2H website as well. 
Funded by NIH U24TR002306
https://ctsa.ncats.nih.gov/cd2h/

**Comment by mellybelly** [comment]
@jaeddy can you work on this one?

**Comment by nicolevasilevsky** [comment]
I created a PR to add the logo to the repo
#129

**Comment by mverzilli** [comment]
@jaeddy once you have clarity on what other orgs logos we need feel free to comment here and the corresponding PR

**Comment by nditada** [comment]
Done!
