### ISSUE TITLE
Guide for translating content

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#12]
We need to start onboarding translators to other languages and it'll be key to have a simple guide on how to register with lokalise, how to get the required permissions and how to go about translating content.

**Comment by drlbln** [comment]
I'd to copy that. I began translating ftc into German yesterday, I'm stuck with the workflow here, tried to email to hello@flattenthecurve.com with no success and would at least like to provide you the litte 1% done so far.

**Comment by mverzilli** [comment]
@nditada this is taken care of AFAICT. Would you close this issue if that's the case?

**Comment by nditada** [comment]
Yes, done, thanks!
