### ISSUE TITLE
Stay home should be THE message front and center for USA.

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#127]
Stay home should be THE message front and center for USA.

The less aggressive measures I published March 6 no longer make sense in lockdown.

**Comment by jmcmurry** [comment]
This whole section needs to be replaced with "Stay Home" until we figure out what we are dealing with. 


Lower your overall risk with everyday choices
Taken together, making safer every-day choices on average — not just this week but for the next several months — can flatten the curve. Continue to support your local economy, but go off peak; staggering by even 15 minutes can reduce crowding. Everything from restaurants to art museums to public transport will be less risky (and more pleasant!) off peak.

Non-contact sports are better than contact ones. E.g., Tennis is better than (>) rugby
Takeout > eat on restaurant patio > eat in restaurant
Video streaming options > movie theatre
Outside events > inside events (small events also are better than large ones)
Delivery/curbside pickup > going in person
Remote observance > religious service attendance
Birthday cupcakes > birthday cake (if candle blowing is involved)
Drink your coffee/beer/cocktail at a table instead > drink your coffee/beer/cocktail at the bar
Live performers are going to be hard hit economically. Consider supporting their work on Patreon, directly via PayPal, or attend only the smaller shows. Promote them on social media. Buy their work directly.

**Comment by pitviper6** [comment]
From the CDC site (https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/summary.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fsummary.html)
'The United States nationally is currently in the initiation phases, but states where community spread is occurring are in the acceleration phase. The duration and severity of each phase can vary depending on the characteristics of the virus and the public health response.'

The United States is a big country, with 50 states, each handling this in a different way. Therefore, community spread is going to be occurring at different rates in different places. It is not known what the after-infection immunity period is like or if this can recur (**not sure about this, needs research**). Therefore, the best thing to do, if not required by your employer, is to stay home until this curve has sufficiently flattened.

Do not dine out.
Do not go to the movies - listen to the radio, watch TV, listen to podcasts, do puzzles, play board games, create an in-home disco.
Do not go to church - use home rituals or streaming services.
Do not go to work unless you must, and when you return have a routine for coming back so as not to bring the virus into your home.
Do not go shopping for non-essentials.
If you get restaurant food delivered, use a service that you can prepay and have the delivery person leave the food on the doorstep. Order well before you want to eat so you can isolate the food for a few hours, then heat it up if needed.
When you go grocery shopping, wear gloves and isolate your purchases (and your gloves!) in a safe spot for a few hours before unpacking.
Get outside! But keep walking. Say hi to people, get some social interaction, but get it in passing. Don't stop and form groups. Make sure and wave to all the pets being walked.

**Comment by emersonthis** [comment]
This feel super critical! Should we use the text provided by @pitviper6 above? Maybe without the sentence that's flagged as needing research?

**Comment by jaysonvirissimo** [comment]
@jmcmurry: looks like this issue was adequately addressed, so we can close this issue.
