### ISSUE TITLE
Reorganize content into new sections

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#130]
**Stylistic update and layout suggestion**
Proposed fix:

This site is full of precious content, but some of it is hard to find. I am proposing a reorganization of the entire site into more intuitive groups:

* What to expect
  * It is here
  * Yes; this is bad
  * This is not a normal flu
  * [government] policies
* Guidance
  * Things you should do
    * ...
  * Things you should NOT do
    * ...
* More resources
* About us
* Contribute

This is a big reorganization, but I think it is important. I am happy to tackle this work myself, but no one should spend time on this before we get an endorsement from the maintainers that this is actually something they want.

**Comment by nditada** [comment]
Done and deployed!

**Comment by emersonthis** [comment]
Woot!!
