### ISSUE TITLE
When to shop when you're at risk

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#134]
If you can afford to have groceries delivered, or can have someone shop for you, so.
Else, if you are elderly or immunocompromised go to the store first thing in the morning when things are less touched.

Some stores are extending their hours for these vulnerable populations.
https://twitter.com/mcuban/status/1239244137834127362

**Comment by nicolevasilevsky** [comment]
Grocery delivery may not be available right now. My Mom is in the bay area and said her grocery delivery was going to take a week. I looked amazon prime in my area and there were no delivery times available.

**Comment by nicolevasilevsky** [comment]
related to https://github.com/flattenthecurve/guide/issues/151
