### ISSUE TITLE
The newsletter link is gone in the Spanish version

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#14]
@seancv can you add the details here?

**Comment by seancv** [comment]
Noticias: Hemos creado un boletín informativo para ayudar a mantenernos al día con los acontecimientos relacionados con COVID19 y los esfuerzos que todos están haciendo para #AplanarLaCurva. Presiona este vínculo  para registrarte (nada de correo spam, nada de publicidad, etc. ¡Y es gratuito!).

Newsletter link: https://flattenthecurve.substack.com

Note: I do not know which words say "you can sign up here" or something to that effect, don't read Spanish. :( But that should be the anchor text. Also bolded!

**Comment by matiasgarciaisaia** [comment]
This has already been fixed in https://github.com/flattenthecurve/guide/blob/184d3af783ffbdb864b263c8c98d428c367ca54e/_content/es/01-context/03-site-intro-and-updates.md 👍
