### ISSUE TITLE
Do | Donate

### ISSUE THREAD

**Issue by tkhans** [flattenthecurve/guide#141]
Perhaps I think under the DO section: Donating / **Donate** should also be included. 

Scenario: The healthcare professionals are running short of N95 Mask and there may be people who've hoarded it/ or having in excess or are not exposed to coronavirus. 

They can come forward and donate it. How the logistics can work - we can figure it out. 

Donate the N95 Mask or any other healthcare device/equipment/safety gear that can support the healthcare professionals. 

Lets group People into three categories. 1)Virus Infected Group 2)Healthcare Professionals 3)Healthy Group. 

The healthy group must extend every possible support to healthcare professionals who in turn can take care of the infected group.

**Comment by tkhans** [comment]
thanks, Will this idea be added to the 'DO' section of flattenthecurve?

**Comment by nicolevasilevsky** [comment]
yes @tkhans
