### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#146]
Now that the structure has been reworked and has room to grow, let's make this thing look like a gorgeous (but simple!) website. 

The #information-architecture team envisioned something like this for the homepage. Keep mobile in mind, 70% of the trafffics is coming from there!!

The 3 "highlights" already have a class" highlight-box" to aid in the layout.
<img width="744" alt="Screen Shot 2020-03-18 at 12 57 55 AM" src="https://user-images.githubusercontent.com/1359189/76923988-bf87bc80-68b3-11ea-9aae-e48f8f44a814.png">

**Comment by jaeddy** [comment]
Just to reiterate that this change should be greatly enabled by the selection of the right "theme" (assuming that we stick to the current Jekyll stack)... this is the demo/docs page for the [Minimal Mistakes theme*](https://mmistakes.github.io/minimal-mistakes/), which I think would be quite compatible with the wireframes above:

![image](https://user-images.githubusercontent.com/5033229/76932220-a37e1e00-68a7-11ea-9eed-0153846a136a.png)

*I don't mean to portray this particular theme as a strong favorite — it just happens to be one I came across that is both relatively minimalist in design and heavily featured in terms of system/service integrations. I'm sure there are other themes that offer similar features and benefits.

**Comment by nditada** [comment]
Yes, this is a totally good fit for the site, but we need to do a careful integration since the current implementation has a deep customization to enable the editorial workflow.

**Comment by emersonthis** [comment]
@nditada Just to clarify: you want the PR for this to modify the _existing_ thing. (Not implement a new theme) Correct?

**Comment by nditada** [comment]
Correct, my guess (I could be wrong) is that implementing a new theme, given the level of customization we did in Jekyll could be tedious and timeconsuming. I think we are better off just modifying what we have, but that theme suggested above is a great inspiration (still away CSS and stuff).

Let's go with small, incremental changes, and deploy often to prod. Don't go for 3 days on a huge redesign.

**Comment by emersonthis** [comment]
Perfect. Understood. Thanks

**Comment by emersonthis** [comment]
~90% of this is addressed in #189 which was just merged. Might make sense to close this and open a new issue just for the remaining navigation change?

**Comment by mverzilli** [comment]
Sure @emersonthis! Do you want to take care of that?

**Comment by emersonthis** [comment]
[Done](https://github.com/flattenthecurve/guide/issues/214).
