### ISSUE TITLE
Parametrize the layout with top

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#147]
This will break once we want another page with its own toc:
https://github.com/flattenthecurve/guide/blob/master/_layouts/page_with_toc.html#L7

Need to parametrize maybe using some convention around the page name? Toc variable is being generated based on the page name already: https://github.com/flattenthecurve/guide/blob/master/_plugins/sections_generator.rb#L14

or maybe change it to a TOC array with one element per page.

**Comment by jaeddy** [comment]
Many Jekyll themes (e.g., [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/)) include functionality for automatically constructing the ToC for a particular page (assuming that individual posts/sections have been labeled as part of that page). If we can figure out how to properly organize content within pages (and/or include the relevant Jekyll front matter for each post), we shouldn't need to do much additional customization of the ToC elements.

**Comment by waj** [comment]
Fixed with 021ebc215fad6e537d69da805d3b1330d219ec82

Any page wanting a TOC now just has to define in the front matter:
```yaml
layout: page_with_toc
toc: true
```
