### ISSUE TITLE
Launching "RESOURCES"

### ISSUE THREAD

**Issue by jackiedelc** [flattenthecurve/guide#163]
Automatic publishing of resources

**Comment by jackiedelc** [comment]
What do we need to do to make this happen? Is someone working on a flow?

**Comment by nditada** [comment]
Let's just setup the flow and start adding content. Any ideas on how we can automatize submission, verification and publishing @mverzilli?

**Comment by mverzilli** [comment]
How about:

1. People submit ideas to a Google Form. We ask for: Language, Region/Country, URL, and title.
2. When someone fills the form, we trigger a message with a button to a #resources channel so that a verifier can check them. 
3. When a verifier gives thumbs up we create an issue in GH in a normalized format (something like: "Add {URL} to Spanish / Argentina").
4. Once there it's up for grabs by any tech volunteer, who can open a PR to add it. One nice aspect of this is that it becomes a very approachable first issue for newcomers or beginners who want to contribute.

TBD:

For 2: 
-We need to identify who would be in this group. As far as I understand we don't want the people in #reviewers to have to spend time and attention to be here, as this is a "lower barrier of entry" section. 
-We also need to determine the tech mechanism to make this trigger happen, but I'm almost sure it's doable with not so much effort.

For 3:
-We need to determine how to automate this. Again, seems quite doable.


We can start working on solving these issues once we agree this is an acceptable workflow. Also, this has a lot of opportunities for further automation, but let's start quickly(ish).

**Comment by matiasgarciaisaia** [comment]
@mverzilli I'd rather update the spreadsheet (or auto-push it somewhere) than send a PR. Maybe a Slack action that adds a "Verified" or something like that. Not sure that we want to keep that on the markdown - I fear any issues with the i18n machinery that we have set up.

But it's a minor issue - let's first decide the UX.

**Comment by jackiedelc** [comment]
The proposed workflow sounds great.

1. I would suggest we collect both city and country. It would be great to 'tag' resources to help visitors navigate them. **Do we have the capability to visually show and filter resources by tags on our platform?** We might develop a set of predefined tags to start (research, actions, news, blogs) and then, have reviewers assigns tags (having contributors their own tags could quickly become a nightmare but having them select from a predefined set could work and then the reviewers verify their choice of tags).

**Comment by nditada** [comment]
That could be a good first approach, but it still involves many manual steps and we are short on people that can write proper md in the repo and push that live...

**Comment by mverzilli** [comment]
I think we already have enough people to tackle those simple PRs. And in the meantime someone with more tech chops can try to streamline the process a bit more.

**Comment by nditada** [comment]
Ok! I created a Jekyll collection sorted by Country under resources and a google form to send submissions. The pending step would be to automatize the generation of .mds from a from entry as much as possible.

**Comment by mverzilli** [comment]
@nditada would you link the google form here?

**Comment by rousik** [comment]
I have a prototype python script that creates md files from the spreadsheets, I will send git pull request shortly so you can review it. Missing bits: 1. slack notifications for when the spreadsheet gets new data, 2. actual verified_by column in the spreadsheet itself

**Comment by rousik** [comment]
Script for pulling all responses from the spreadsheet into md files is here:
https://github.com/flattenthecurve/guide/pull/241

**Comment by rousik** [comment]
And the spreadsheet responses are now hooked to post updates on #resources channel on Slack. When the import_resources.py script is run, it will pull in all the rows into md files. Currently the ApprovedBy verification is disabled but it's a very easy change to fix that.

**Comment by nditada** [comment]
> would you link the google form here?

https://docs.google.com/spreadsheets/d/1QSQgxceR8BL03qsR-GY8bw4tsdsx30kovU7wVXPUcxo/edit#gid=505503892

**Comment by nditada** [comment]
What is missing to wrap this up? A way to trigger automatically the py script?

**Comment by rousik** [comment]
1. pull request needs to be approved and integrated: https://github.com/flattenthecurve/guide/pull/248
2. documentation of the process needs to be put up on the wiki
3. we need set of volunteers or process to verify/approve incoming resources
4. we need to either run the script by hand or automatically via cron

**Comment by rousik** [comment]
I think we can leave (4) as manual ops while the rate of incoming resources is low

**Comment by mverzilli** [comment]
For 4 we can simply add a daily reminder in #devops so that someone remembers to run it.

I'll do my best to take care of 1 and 2 tonight.

**Comment by matiasgarciaisaia** [comment]
I've added a [temporary] reminder in the channel. Whenever we have (2) sorted out, we can update it with better instructions.

**Comment by nditada** [comment]
Great, and (3) can be left out, we have already agreed internally that the content is self-moderated and there's a disclaimer on the page about that.

**Comment by rousik** [comment]
The script has been merged to head. I have described the current protocol here:
https://github.com/flattenthecurve/guide/wiki/Processes#adding-content-to-resources-page

**Comment by rousik** [comment]
The next steps here are:
1. try to improve the process for aggregating the new resources (better slack notification, pre-populating approved resources page)
2. regenerate current _resources/ contents
3. look into automating the script. I was thinking that it could create PRs if there are some changes. Then all we'd have to do is approve those when they show up.

**Comment by rousik** [comment]
Google Apps Script now automatically copies content into the Approved Resources upon submission and I have PR with the github action that should automatically run the import_resources.sh and create Pull Requests. This should be the only step necessary for human intervention w.r.t. importing new resources.

**Comment by rousik** [comment]
This should be done now. The entire setup is documented here:
https://github.com/flattenthecurve/guide/wiki/Processes#resources

The only remaining manual step is approving PRs that are automatically generated each day if new resources are coming. We might consider running the action more frequently as it doesn't result in PRs in case no new resources are available.
