### ISSUE TITLE
Titles look too big and spaced on mobile

### ISSUE THREAD

**Issue by waj** [flattenthecurve/guide#174]
![image (1)](https://user-images.githubusercontent.com/22697/77186909-6639ac00-6ab2-11ea-91e1-25baba0e1cd8.png)

**Stylistic update and layout suggestion**
Proposed fix:
This is how it looks with default font size for `H1` and with `line-height: normal`
![image (2)](https://user-images.githubusercontent.com/22697/77186962-823d4d80-6ab2-11ea-8fed-09d32341c47b.png)

**Comment by jmcmurry** [comment]
agree

**Comment by mverzilli** [comment]
This is now fixed AFAICT. Please reopen if you don't agree.
