### ISSUE TITLE
Add a "Myths" section

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#175]
@emersonthis made [this site](https://coviddenial.org/) before working on this project. The content is 100% up for grabs if we want to fold it into this site. The goal is to provide concise, informed responses to some of the popular _wrong_ (and dangerous) ideas that people have.

Proposal:
* Add a new sub-section called **Myths**, probably at the bottom of the **Act & Prepare** page
* Use the same format: title followed by the explanatory text, but no colors on the titles (to differentiate from the DOs and DONTs section
* Make sure each title is linkable. One of the biggest values of this content is that it's a quick resource that can be shared on social media or via email. (We were getting tired of refuting the same misconceptions again and again)
* Update the sources to be more current (also note that a few of them currently cite this site)

cc @mellybelly

**Comment by emersonthis** [comment]
For convenience, here's the content:

## It's just the flu.

It isn't! The severity is more similar to pneumonia. Many patients require respiratory support. It is also more contagious than the common flu.
Sources: [1] [2]

## I'm young and healthy so I don't need to care.

Young and healthy people are generally less likely to die if infected, but this is not the point! Treatable conditions easily become deadly if the health system collapses. We are not equipped to handle hundreds or thousands of respiratory patients at the same time. In places where the outbreak is full-blown, the medical facilities are completely overwhelmed. Patients are in hallways and gymnasiums. Doctors are being forced to ration limited resources like ventilators, oxygen, and even basic supplies like masks and gloves. You might be lucky, but it will likely be at the expense of others in your community.
Sources: [1]

## There are no infections near me.

There are almost definitely infections near you! But you cannot see them yet because there is a two week delay between the time of infection and when someone shows symptoms. During that time, the infected person is contagious and spreading the infection. For every single diagnosed case of COVID-19, there are likely hundreds of undiagnosed cases. For this reason, our only chance to avoid a massive public health disaster is if we take preventative measures before we see it everywhere.
Sources: [1]

## I cannot afford to stay home or close my small business.

This is a public health and economic crisis. Everyone is impacted. All the evidence indicates that the pandemic will force most businesses to close soon whether we want to or not. Ideally, public officials will take decisive steps to mandate social distancing as it is currently one of the only tools available to flatten the curve of infections and save lives. We can't opt out of this pandemic, but we can opt out of unnecessary risk of infection. If a tsunami was coming towards your town, would you complain about the economic cost of evacuating? This outbreak is an invisible tsunami, but unlike the countries where it hit first, we have advanced warning. The US wasted much of that head start with inaction, but one of the lessons becoming increasingly clear is that every single day counts.
Sources: [1] [2]

## The media is overblowing this. People are panicking.

There has been a lot of misinformation and the media is predisposed to fearmongering. But this does not change the fact that the situation is very serious. Panicking is dangerous and unproductive, but so is ignorance and inaction.
Sources: [1]

## There's no point in me staying home because some people aren't.

 The goal of social distancing is to slow the rate of infections and more is better, but it is not "all or nothing." In the context of an exponential growth pattern, even small reductions have large effects. If the wellbeing of your greater community doesn't motivate you, remember that you are risking infecting yourself and your family.

**Comment by emersonthis** [comment]
(This is an easy ticket, but we should wait to get a 👍 from @nditada or someone on the core team to confirm they actually want this PR.)

**Comment by jmcmurry** [comment]
This is great, I +1. Here is a good graph in here to show the numbers.
https://www.washingtonpost.com/health/2020/03/19/younger-adults-are-large-percentage-coronavirus-hospitalizations-united-states-according-new-cdc-data/
It is pretty out of focus

**Comment by nditada** [comment]
I love this! Will get approvals and come back!

**Comment by nicolevasilevsky** [comment]
I approve

**Comment by nicolevasilevsky** [comment]
@emersonthis looks like you may have some references above, can you share those?

**Comment by emersonthis** [comment]
I’m afk at the moment but you can see them on the live site linked in the issue. You can also find them in the GitHub repo (linked on the site). I’ll add them to this issue later if someone else doesn’t get to it first.

**Comment by emersonthis** [comment]
I just updated the comment above with the citations from my cite. One is missing and some could be better for sure.
