### ISSUE TITLE
Title in header breaks on small screens

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#186]
**Bug:**
The title in the header breaks awkwardly on smaller screens (which is most of our traffic).

<img width="377" alt="Screen Shot 2020-03-20 at 5 24 03 PM" src="https://user-images.githubusercontent.com/1728139/77215139-ddca0400-6acf-11ea-92d1-46e1c5026ad6.png">

<img width="371" alt="Screen Shot 2020-03-20 at 5 24 21 PM" src="https://user-images.githubusercontent.com/1728139/77215145-e1f62180-6acf-11ea-816b-5139fc246604.png">

**Suggested fix:**

* Consider shortening the title. Could it just say "Flatten the curve"? 
* Add responsive styles to compress the title / header on smaller screens.

**Comment by weltyj** [comment]
This is the same bug reported in #172

**Comment by emersonthis** [comment]
Yup. Just saw. Closing
