### ISSUE TITLE
No TOC for Act & Prepare page on mobile

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#190]
It's a long page with a lot going on...

On larger screens, we show a nice tree on the left side to jump directly to sections and subsections. But this doesn't appear on mobile, which means there's no way to discover the lower content without reading through the entire page!

Most of our users are on mobile devices, so this feels like a big problem.

<img width="418" alt="Screen Shot 2020-03-20 at 10 17 27 PM" src="https://user-images.githubusercontent.com/1728139/77220070-8771bb00-6af9-11ea-9379-f7e3b0c64110.png">

**Comment by weltyj** [comment]
I now have a script for parsing all markdown files on a folder by folder basis, so if the solution for this is changes to the markdown files it could quite possibly be automated instead of manual edits to affected files in the (4) languages.
