### ISSUE TITLE
Policies that influence pandemic control

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#200]
Worst  | Best | Note
-----|-----|-----
No paid sick leave | Universal guaranteed paid sick leave
Paid sick leave on the order of days | Paid sick leave on the order of weeks
No family leave, paid or unpaid, to care for sick members | Paid family leave to care for sick members
No financial or operational support for people who should self-quarantine (Without this, infected people ignore quarantine because they need to eat.) | Coordinated financial and operational support for people who should self-quarantine | [1]
Large numbers of people without access to health care (whether through insurance, or single payer) | Universal coverage|  [2]
Health insurance tied to employment   | Health insurance not tied to employment | [3]
Strong emphasis on individual civil liberties | Strong emphasis on collective good 

[1] Many people are uninsured. Given where things are right now (cryptic transmission and no available vaccine), the insurance companies may have a moral obligation but have no financial incentive to improve testing and ensure access to care.
[2] Without this, infected people ignore quarantine because they need to eat.)
[3] In the USA insurance is tied to their employment, so when they get sick they are also vulnerable to bankruptcy. In a pandemic year this is devastating for an economy.

Note that this should not be interpreted to mean that pandemic control is the only consideration for these policies, simply that we should expect pandemic impacts to be worse in certain contexts as a result.

**Comment by steesdale** [comment]
Suggest leading with the positive over the negative.   

Also, these are secondary policies that affect pandemic control.  I would expect to see things more directly engaged too.  Contract tracing, surveillance, vaccine developement, infection control, accessible/extensive testing,  etc.. There is a nice list here by the Resovle to Save Lives team... https://www.cnn.com/2020/03/20/health/coronavirus-response-must-adapt-frieden-analysis/index.html

**Comment by nditada** [comment]
I am not sure I follow what this issue proposes to do, is this a discussion on adding that table as content somewhere? If so, where?

**Comment by jmcmurry** [comment]
This is in lieu of the current section about policies, both in order to make it more internationally relevant, and in order to make it more about the facts than the implications. We could cut it completely, however the reason I had written it in the first place was to point out that the breakwaters that could have slowed this pandemic in the USA are simply not there. Ergo, personal action is a matter of utmost importance.
