### ISSUE TITLE
Please explicate: "Don’t use “concern” as a smoke screen for racism"

### ISSUE THREAD

**Issue by codejack42** [flattenthecurve/guide#202]
**Content to be added or changed:**

Thank you for daring to use the term 'racist', which (despite the superabundance of racism around us) is too often shied away from as if it were a dirty word.

Every time I read the "Do not be racist" section, when I see
"Don’t use “concern” as a smoke screen for racism"
my response is, "Wait. What? I don't know what this means."

I'm willing to admit that I'm a thickheaded idiot. I'm also willing to bet that there are a lot of other thickheaded idiots out there reading. I strive to keep away from any racist anything and I continually encourage others to do likewise, and I'm certain that the more, and the clearer, anti-racist guidance we can get, the better! I'm also certain that what's being said is really important, and I'm infinity percent down with including strong anti-racism guidance. However, I am somehow managing to miss the very obvious meaning, and I must therefore conclude that my thickheaded idiot brethren and sistren out there in Pandemic Land are missing the very obvious meaning also. Subtlety and reading between the lines aren't everybody's strong suit.

Thank you for your work and for your kindness.

**Comment by jaysonvirissimo** [comment]
You are not alone. It’s confusing to me as well. Perhaps the original author could add further context?

**Comment by jmcmurry** [comment]
What I have seen is people suggesting we out of "concern" for the health of Americans, refuse to shop at Asian markets, interact with Asians, etc. Open to ways to rephrase. I see how this is confusing.

**Comment by codejack42** [comment]
@jmcmurry Great, thank you, understood. I'll take a shot at re-phrasing. Use (or not) as you will.

++++ BEGIN RE-PHRASE DRAFT ++++

COVID-19 isn't racist. You shouldn't be racist either.

The only way through this mess is together.

If you're truly concerned about the spread of COVID-19 you must recognize that COVID-19 doesn't play favorites -- it infects all peoples equally regardless of race, ethnicity, or nationality. Everyone is equally in need of protection from this terrible disease.

There have been incidents in various countries where people of Chinese or East Asian ancestry have been shunned, abandoned, bullied, threatened, or beaten because someone was afraid that the "Chinese-looking" person might be infected with COVID-19 or because someone was angry that the COVID-19 virus originated in China.

Let's talk about why these racist assumptions are factually incorrect and why these racist behaviors are socially wrong. The facts:

   * No single race, ethnicity, or nationality is more likely to be infected with COVID-19, spread COVID-19, or become sick with COVID-19. Each of us, no matter our race, ethnicity, or nationality, pose equal infection risk to everyone else, regardless of their race, ethnicity, or nationality. The person most likely to be infected near you might easily be in your own mirror, regardless of your race, ethnicity, or nationality, and it would be factually incorrect and socially wrong to blame you for that.

   * No single race, ethnicity, or nationality is to blame for where COVID-19 first occurred or where it has since spread. Viruses come into being naturally, and spread naturally, according to their own rules. The next bad virus could just as easily come from your home town, regardless of your race, ethnicity, or nationality, and it would be factually incorrect and socially wrong to blame you for that.

Racist assumptions lead to racist behavior. Racist behavior divides us, and in this pandemic situation, definitely works against us. If we divide ourselves according to race, ethnicity, or nationality, the virus wins and we all lose, plain and simple. If we unite ourselves regardless of race, ethnicity, or nationality, the virus loses and we all win.

If a virus can act without racism, you can too.
++++ END RE-PHRASE DRAFT ++++

**Comment by jmcmurry** [comment]
I endorse this sentiment 150%, however it is very long. I love the closer though and would stick with just that.

"Racist assumptions lead to racist behavior. Racist behavior divides us, and in this pandemic situation, definitely works against us. If we divide ourselves according to race, ethnicity, or nationality, the virus wins and we all lose, plain and simple. If we unite ourselves regardless of race, ethnicity, or nationality, the virus loses and we all win."

**Comment by codejack42** [comment]
Thumbs up on your view re length, closer, etc. I'm also happy to condense/re-write the "very long" draft I wrote previously. The existing closer is 56 words. If that's already the right message in the right number of words, cool, nothing else for me to do. But if not quite you want, tell me how many words you want and anything that's a must-have in those words, and I will produce the thing that you want.

If sticking with the existing closer I'd suggest changing the singular 'racist behavior' to the plural 'racist behaviors'. Because it's good to subtly remind that there are _lots_ of racist behaviors in the world around us and we can strive to eliminate all of them. Here's that change:

"Racist assumptions lead to racist behaviors. Racist behaviors divide us, and in this pandemic situation, definitely work against us. If we divide ourselves according to race, ethnicity, or nationality, the virus wins and we all lose, plain and simple. If we unite ourselves regardless of race, ethnicity, or nationality, the virus loses and we all win."

PS: if you want a bit or blurb on pretty much any topic, feel free to tell me the topic and how many words you want and I can write it, especially if you want to point me toward the source material you believe is best and/or most accurate.

Thank you for your work and caring.

**Comment by pitviper6** [comment]
Changed to the new paragraph and created pull request #257 (wasn't able to link it)

**Comment by jaysonvirissimo** [comment]
@codejack42 we can close this now @pitviper6's changes are in production. 👍
