### ISSUE TITLE
Pro cloth-mask section needed.

### ISSUE THREAD

**Issue by paul-hammant** [flattenthecurve/guide#203]
**In the last two days:**

US health services group Deaconess Health Systems shares a **cloth** mask design as part of their appeal for cloth masks (March 20):

PDF: https://www.deaconess.com/How-to-make-a-Face-Mask/Documents-Mask/Mask-Information Video: https://youtu.be/9tBg0Os5FWQ

US health services group Providence shares a **cloth** mask design video (March 21) - part of their "100 million mask" initiative:

Video: https://vimeo.com/399324367/13cd93f150

**flattenthecurve.com** comes across as anti-mask, a little? A lot?  Site needs to change to mirror what's happening out there re cloth masks, and the home made potential of that.

**Comment by paul-hammant** [comment]
And because there are going to be those that argue back, the studies are on my site https://cv-masks.github.io

**Comment by jaysonvirissimo** [comment]
Related: https://github.com/flattenthecurve/guide/pull/242

**Comment by jaysonvirissimo** [comment]
This issue can be closed now.

@steesdale, @mverzilli
