### ISSUE TITLE
Moving content on homepage into a new tab "Reality"

### ISSUE THREAD

**Issue by jackiedelc** [flattenthecurve/guide#206]
Please report the issue under the appropriate header below.

**Content to be added or changed:**

Please move all content under "Yes, this is bad" on the Homepage to a new tab called "Reality" (we can change the name of this tab as we go along since we have not agreed on it yet... we have agreed on the content being moved). Please also remove this text:

"About the authors
More about the authors here

Affiliations
Please note, we are not speaking on behalf of any institution.

We are doing out best to include only trusted sources and maintain the site updated. Please let us know if there are issues with the veracity or currency of the content; if you are a virologist / public health professional, etc., and wish to contribute to it, please go here."

**Stylistic update and layout suggestion**
Proposed fix: Please add a new tab called "Reality" as the tab before (and to the left of) "Prepare & Act" on the header. Please populate it with all text on the homepage under "Yes, this is bad"

**Comment by emersonthis** [comment]
It appears that a variation of this happened already when the homepage launched... @jackiedelc please feel free to re-open this or perhaps a new issue if everything wasn't adequately addressed.
