### ISSUE TITLE
Increase visibility of "how to contribute with content, reviews, translations"

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#21]

**Comment by nicolevasilevsky** [comment]
There are two sections on how to contribute, near the top and at the bottom. I will do a pull request to add a link from the top of the doc to the bottom of the doc.

@nditada what else did you have in mind to increase the visibility? And were you referring to the contribute section at the top of the doc or the bottom?

**Comment by jaysonvirissimo** [comment]
@nditada, @nicolevasilevsky: looks like we can close out this issue now.
