### ISSUE TITLE
Title wraps and obscures language selection links on narrow screen mobile device

### ISSUE THREAD

**Issue by weltyj** [flattenthecurve/guide#217]
**Bug:**
The new title is wrapping over and obscuring the "english" and "espanol" language links on my samsung mini -- (screen width 540 pixels), the english and espanol language links are not functional.

**Suggested fix:**
I don't know for sure, 1) maybe the Jekyll title bar height can be increased so when the title wraps it won't wrap over the language links.  2) add a vertical space before the language links?  (that'd look bad) 3) create two "invisible" languages, pushing the real languages to the right and making them accessible. 4) how about putting the language links in the menu, which will protect them from being overwritten?

None of those sound like great solutions, but maybe 1) is best, 4) might get things working fast.  If you come up with a solution, I can test it on a preview before releasing a fix into the wild...

**Comment by mverzilli** [comment]
Would you provide a snapshot? I'm not being able to reproduce this at the moment

**Comment by weltyj** [comment]
![Screenshot_2020-03-23-12-18-42](https://user-images.githubusercontent.com/34079596/77355377-91660a80-6d01-11ea-89ee-e7ec6cac653c.png)

**Comment by mverzilli** [comment]
Sorry if this is a silly question, but I'm not sure why you closed the issue?

**Comment by weltyj** [comment]
Doh!  I fat fingered it.  Was in a rush to go for a walk before  the heavy rain came
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 23, 2020 at 12:34 PM, Martin Verzilli<notifications@github.com> wrote:   


Sorry if this is a silly question, but I'm not sure why you closed the issue?

**Comment by weltyj** [comment]
When you do a preview snapshot, does that use a "cpu" cycle in Zeit?   If so -- when you have a branch with a fix, first let me know and I'll put that branch on my local repo and test it locally, saving a Zeit cpu cycle

**Comment by weltyj** [comment]
Suggested fix:

line 40 in guide/_sass/minima/_header.scss  change:
    @include relative-font-size(1.2);
to
    @include relative-font-size(1.1);

That line affects the font size on small screen devices.

It now looks ok in all languages on my 540px wide screen.

Would you like me to make a branch and do a PR?

...ramping up my understanding of Jekyll from "no clue" to "extremely minimal" ;-)

**Comment by weltyj** [comment]
I pushed a branch to fix this bug as I decribed above.   Branch named issue_217

**Comment by mverzilli** [comment]
Great, merged!
