### ISSUE TITLE
Submitted a pull request for some edits...not sure how you guys want to manage collaboration.

### ISSUE THREAD

**Issue by natecostello** [flattenthecurve/guide#23]
I made some minor edits to try minimize what would be perceived as a political position on single-payer healthcare to raise mass appeal and adoption.  I'm not sure if pull requests are how you guys intend for people to contribute or not.   #flattenthecurve.

Pull request: https://github.com/flattenthecurve/guide/pull/20

**Comment by nditada** [comment]
Thanks @natecostello! Merged already.
