### ISSUE TITLE
Consider adding "Do take vitamin D supplements if you are likely deficient"

### ISSUE THREAD

**Issue by jaysonvirissimo** [flattenthecurve/guide#255]
**Content to be added or changed:**
Taking vitamin D supplements likely reduces your risk of complications caused by coronavirus.
Here is some corroborating sources include:

[Association between serum concentration of 25-hydroxyvitamin D and community-acquired pneumonia: a case-control study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5692194/)
> According to findings, a low level of 25(OH)D is associated with a higher incidence of CAP and more severe disease. It is recommended to pay more attention to vitamin D deficiency in infectious diseases, particularly in CAP patients.

[Relationship Between Vitamin D Status and Viral Pneumonia in Children](https://www.liebertpub.com/doi/abs/10.1089/ped.2017.0750?journalCode=ped)
> As vitamin D status decreased, the odds ratio (95% confidence interval) for VP showed an increasing trend [sufficiency (0.3; 0.2–0.5), insufficiency (0.9; 0.6–1.3), deficiency (2.0; 1.3–2.9), and severe deficiency (51.7; 7.2–372.2)]. The median (IQR) serum 25(OH)D level in the VP subgroup who accepted mechanical ventilation was significantly lower than that in the nonmechanical ventilation subgroup [12.9(6.5–22.5) ng/mL versus 20.8 (14.2–28.0) ng/mL] (P < 0.001). Poor vitamin D status might be related to the susceptibility and severity of VP in children.

[Vitamin D supplementation and respiratory infections in children](https://www.who.int/elena/titles/vitamind_pneumonia_children/en/)
> In addition to causing rickets, vitamin D deficiency has been linked to respiratory infections such as pneumonia, tuberculosis and bronchiolitis.

**Comment by jmcmurry** [comment]
Good call; however, vitamin D is manufactured by the body in response to sunlight, so we need to also advise that people also not underestimate the importance of the outdoors. "Get outside, get into nature, and make your own discoveries" - Dr. Scott Sampson

**Comment by jaysonvirissimo** [comment]
In that case, maybe it should read “Do ensure you get enough vitamin D” and then give a few strategies including supplements and sunlight.

**Comment by jmcmurry** [comment]
Indeed; outdoors is also vital for people's mental health. Great summary here: https://www.washingtonpost.com/outlook/2020/03/24/dont-cancel-outdoors-we-need-them-stay-sane/
