### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#256]
![unnamed](https://user-images.githubusercontent.com/1359189/77799923-9229d400-7054-11ea-83de-9d6901d37a65.png)

**Comment by nditada** [comment]
![unnamed-2](https://user-images.githubusercontent.com/1359189/77799958-a1108680-7054-11ea-9b55-936ed4706674.png)

**Comment by rousik** [comment]
New page redesigns removes this text.
