### ISSUE TITLE
Very nice video for lay people explaining exponential growth & FTC concepts

### ISSUE THREAD

**Issue by weltyj** [flattenthecurve/guide#259]
**Content to be added or changed:**
For Resources.

https://www.youtube.com/watch?v=fgBla7RepXU

**Comment by rousik** [comment]
I have added this video to Resources and it should be automatically integrated in a day or so.

**Comment by rousik** [comment]
Feel free to reopen this bug in case we want to surface this video more prominently - which might be a good idea given that it kind of summarizes what all of this is about.
