### ISSUE TITLE
add jazz hands to "get creative with zero-contact greetings"

### ISSUE THREAD

**Issue by nicolevasilevsky** [flattenthecurve/guide#26]
This is my favorite article I have read so far:
https://www.thebroadwaybeat.com/post/cdc-urges-citizens-to-avoid-spreading-coronavirus-by-greeting-exclusively-with-jazz-hands

![image](https://user-images.githubusercontent.com/6722114/76670743-6e906500-654f-11ea-8de5-a8efda123c19.png)

**Comment by jmcmurry** [comment]
We definitely need a new jazzhands emoji
