### ISSUE TITLE
Explain what curve should be flattened on the index page

### ISSUE THREAD

**Issue by jaysonvirissimo** [flattenthecurve/guide#276]
**Content to be added or changed:**
When a new user visits the website they see the following:
<img width="1115" alt="index-page" src="https://user-images.githubusercontent.com/1292454/78208147-81180300-7458-11ea-8619-663fb26e09a1.png">
But...this doesn't explain what curve we're talking about, nor why it should be flattened.
I don't think we should assume users already have this knowledge when they first visit.
Perhaps adding a small explanatory sentence or showing the diagram might help things.

**Comment by jaysonvirissimo** [comment]
A higher res version of this would work, I think:
![1500x500](https://user-images.githubusercontent.com/1292454/78411122-762db180-75c3-11ea-8edb-de7b0ca1d20b.jpeg)

**Comment by emersonthis** [comment]
@jaysonvirissimo How about if we reword the italicized text right below "Flatten the Curve" to be more explanatory in the way you requested. Any ideas?

**Comment by jaysonvirissimo** [comment]
I'm sure a marketing person could do better, but to get us started:
> Graphing cases over time results in a bell-shaped curve. If the curve is tall and skinny, our hospitals will be overwhelmed, but if it is flat and long they can treat all the sick meaning fewer lives lost.

**Comment by emersonthis** [comment]
There was a ton of thought and discussion about the newest iteration of the homepage. I can't summarize it all here, but the short explanation is that we wanted to keep the homepage super focused on achieving [the core mission of the site](https://www.flattenthecurve.com/about/#purpose), which (despite the name) is *not* actually teaching people about what the curve is. We're prioritizing the _what (to do)_ over the _why_. Contextualizing what "the curve" is doesn't conflict with this goal, but focusing the homepage on that chart again would. So my recommendation is that we solve your original concern by carefully adjusting this phrase:

> Up to date information about COVID-19 for everyone, verified by medical experts.

**Comment by jaysonvirissimo** [comment]
@emersonthis: understood. How about this then: 
> Up to date information about COVID-19, verified by experts, so you can help slow the spread and prevent hospitals from being overwhelmed.

**Comment by emersonthis** [comment]
That sounds pretty good to me. I might say "so we can slow the spread" so it's a little more direct and personal. If you can get some buy-in from people in charge I endorse this change.
