### ISSUE TITLE
Handle accents correctly in uppercase transformed text

### ISSUE THREAD

**Issue by mpitid** [flattenthecurve/guide#284]
**Bug:**
Languages with different accent rules for uppercase like Greek are not handled correctly when text-transform: uppercase is used.

**Suggested fix:**
Possible workarounds here: https://stackoverflow.com/questions/28783259/how-do-i-make-text-transformuppercase-work-properly-with-greek/28790147#28790147

I can see the  following template but when I inspect the DOM I see lang=en on the element:

```
./_layouts/default.html:2:<html lang="{{ page.lang | default: site.lang | default: 'en' }}">
```
![devtools screenshot](https://user-images.githubusercontent.com/211314/78406781-44d0d800-75fb-11ea-8e1e-c6973c40f2ff.png)

**Comment by mpitid** [comment]
Testing with Chrome DevTools this appears to work (note you need to edit the text as well for it to pick up the attribute change).

**Comment by mpitid** [comment]
This appears to only be an issue on the landing page, other sub-pages have the correct page.lang value.

**Comment by emersonthis** [comment]
@mpitid Is it accurate to restate the issue like this: the lang attribute is not being set to the correct language on the homepage?

**Comment by mpitid** [comment]
I think so yes.

**Comment by emersonthis** [comment]
@mpitid When you have a second, please look at the screenshots (or the preview site) from [this PR](https://github.com/flattenthecurve/guide/pull/297) and confirm if the accents look correct now.

**Comment by mpitid** [comment]
Looks good to me, but see comment on the PR.
