### ISSUE TITLE
Reorganize DOs and DON'Ts content

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#294]
It's been widely agreed that the current structure no longer makes sense. The plan is to divide the content into smaller thematic "chunks". The exact strategy is still being discussed [on Slack](https://flatten-the-curve.slack.com/archives/CV619KQUB/p1585887711004300).

This issue will get updated as that work takes shape...

**Comment by emersonthis** [comment]
I just invited @ShaynaKorol and Chelsea to this doc: https://docs.google.com/document/d/10-beltiY0aqNrZSmm3i6bXtyov-MDfqan4zL2sXLdlU/edit#

**Comment by emersonthis** [comment]
From the doc linked above... The links point to the existing content associated with that item. The items with `?` I'm considering removing (awaiting more feedback).

### How to stay safe


*   [Stay home](https://www.flattenthecurve.com/act-and-prepare/#stay-home)
*   [Wash your hands](https://www.flattenthecurve.com/act-and-prepare/#wash-your-hands)
*   [Don’t touch your face](https://www.flattenthecurve.com/act-and-prepare/#do-not-touch-your-face)
*   [Where a facemask in public](https://www.flattenthecurve.com/act-and-prepare/#wear-a-facemask-when-in-public)
*   [Prepare a “hot zone” in your home](https://www.flattenthecurve.com/act-and-prepare/#hot-zone)
*   [Get your flu shot](https://www.flattenthecurve.com/act-and-prepare/#get-your-flu-shot)?
*   [“Flu buddy”](https://www.flattenthecurve.com/act-and-prepare/#flu-buddy)?
*   [Vitamin-D](https://www.flattenthecurve.com/act-and-prepare/#get-enough-vitamin-d)?
*   [Don't wait until it's too late](https://www.flattenthecurve.com/act-and-prepare/#do-not)?


### Household practices



*   [Do not hoard supplies](https://www.flattenthecurve.com/act-and-prepare/#do-not-hoard-supplies) 
*   Shop at off-peak times
*   Consider having groceries delivered
*   [Clean and disinfect regularly...](https://www.flattenthecurve.com/act-and-prepare/#your-home)
*   [Don’t mix cleaning products](https://www.flattenthecurve.com/act-and-prepare/#do-not-mix-cleaning-products)


### If you get sick



*   [Call ahead to your doctor](https://www.flattenthecurve.com/act-and-prepare/#call-ahead)
*   [Monitor your symptoms](https://www.flattenthecurve.com/act-and-prepare/#call-ahead)
*   [Link to hot zone section above]
*   [Link to self-quarantine section below]


### Support the greater effort



*   [Cancel unnecessary medical visits](https://www.flattenthecurve.com/act-and-prepare/#medic-visits)
*   Spread accurate information? / Don’t spread misinformation
*   [Quarantine yourself if you feel sick in any way.](https://www.flattenthecurve.com/act-and-prepare/#if-you-are-sick)
*   [Lobby your government for research and smart policies](https://www.flattenthecurve.com/act-and-prepare/#spread-the-word)
*   [Be kind to others](https://www.flattenthecurve.com/act-and-prepare/#look-beyond-yourself)
*   [Do not be racist](https://www.flattenthecurve.com/act-and-prepare/#do-not-be-racist)


### Tips to stay sane and comfortable



*   [Ignore “secret treatments” and home remedies](https://www.flattenthecurve.com/act-and-prepare/#be-on-guard)
*   [Do not binge on news or social media](https://www.flattenthecurve.com/act-and-prepare/#be-present-do-not-binge-the-news)


### Myths



*   [no changes]

**Comment by emersonthis** [comment]
Planning ahead for when we groom the individual entries... I propose that each of the following criteria should be met by every item we include on this page:

### Specifically relevant to COVID-19
No generalized advice that always applies, like "apply sunscreen"...

### Important and impactful
No trivial advice that doesn't really matter

### Useful to a general audience of laypeople
Not the place for complex techncial recommendations to doctors or scientists

### Objectively true and consistent with trusted guidelines
No subjective opinions or unsubstantiated theories.

cc @nditada @mellybelly

**Comment by jmcmurry** [comment]
Thanks for looking at this this re-org looks great; I would, however like to keep the pandemic pal section. Was there anything else that was cut?

**Comment by emersonthis** [comment]
@jmcmurry The Vitamin-D post was removed.
