### ISSUE TITLE
Tons of console errors starting docker

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#299]
When I run `docker-compose up` I see this...

<img width="990" alt="Screen Shot 2020-04-04 at 4 06 06 PM" src="https://user-images.githubusercontent.com/1728139/78464734-cbd88b80-76a1-11ea-8c8f-578f64871010.png">

I'm on a Mac...
MacOS v10.15.3
Docker Desktop v2.2.0.4

**Comment by jaysonvirissimo** [comment]
@emersonthis: YAML gives special meaning to the `:` character, so if you want to use it in the name itself, you have to wrap the value in double quotes. Please checkout the branch from my PR and verify that it fixes the console errors you experienced.

👍

**Comment by rousik** [comment]
My recent PRs should have fixed this issue.
