### ISSUE TITLE
Consider switching license to CC-BY

### ISSUE THREAD

**Issue by ShaneCurcuru** [flattenthecurve/guide#342]
Please report the issue under the appropriate header below.

**Content to be added or changed:**
Change LICENSE to CC-BY-NC instead of CC-BY-NC-ND.

Unless there is a specific need to prevent remixing, use of CC-BY-NC-ND prevents most other websites or mutual aid groups from being able to incorporate any of your site content into their work.  If this is meant to be a sharable resource meant for people to help themselves and others teach reliable and scientifically backed data - like you do :tada: - then it would be more useful to allow sharing.

In particular, people who aren't going to respect licenses anyway will re-share no matter what, but people who do respect licenses are less likely to share or use your work elsewhere because they're concerned about what NoDerivatives means.

Thanks for keeping this so organized, well presented, and backed with science! 

**Typo to be fixed:**

Typo: 

Proposed fix: 

**Grammar error:**

Error:

Proposed fix:

**Stylistic update and layout suggestion**
Proposed fix:

**Comment by lgrn** [comment]
I would caution against using CC-BY-NC and instead suggest CC-BY just like @brian-bot. There are multiple issues with the NonCommercial license, one of them being that it's not clearly defined or understood by most what this addition means. From Wikipedia:

> Erik Möller _[former deputy director of the Wikimedia Foundation (WMF)]_ raised concerns about the use of Creative Commons' non-commercial license. Works distributed under the Creative Commons Non-Commercial license are not compatible with many open-content sites, including Wikipedia, which explicitly allow and encourage some commercial uses. Möller explained that "the people who are likely to be hurt by an -NC license are not large corporations, but small publications like weblogs, advertising-funded radio stations, or local newspapers."

For proponents of NC I also recommend looking at: https://wiki.creativecommons.org/wiki/NonCommercial_interpretation#Choosing_NC_for_your_content

[This article](https://www.techdirt.com/articles/20140326/11405526695/german-court-says-creative-commons-non-commercial-licenses-must-be-purely-personal-use.shtml) also gives an example in where a German court interpreted the license very strictly:

> The case concerned the use of a photo from Flickr, released under a CC-BY-NC license. The photo appeared on the Web site of Deutschlandradio, part of the German public broadcaster -- a non-commercial organization, that is. Alongside the photo, Deutschlandradio's Web site included the name of the artist, the license, and a link to its terms. Despite this, the photographer demanded 310 Euros plus costs on the grounds that Deutschlandradio had used the photo for commercial purposes.

> The public broadcaster pointed out that there was no charge for its Web site, there was no advertising, and no sponsorship. Nonetheless, the judge agreed it should be treated as a commercial use. In coming to this view, the judge drew on German law, which defined "non-commercial" as purely for personal use, and excluded all commercial use in the "generally accepted sense", and that apparently included radio stations, irrespective of how they were funded. 

Judging by the purpose of this text and what (I assume) we want to achieve with it, a non-commercial license does not make sense to me.

**Comment by mellybelly** [comment]
+1 to CC-BY

**Comment by jmcmurry** [comment]
CC-0 is my preference, but +1 to CC-BY

**Comment by nditada** [comment]
I am not a lawyer, but removing the no derivatives would allow people to actually change the content on top of the already permitted re-distribution. If I were one of the scientists "signing" the content, I would not want that. Others might know better the liability implications of those two components. My suggestion of the ND was an attempt to protect the team putting their name on the content.

**Comment by rousik** [comment]
As I see it there are two things we are trying to resolve here:
1. Removal of NC, because of its legal complications/problems. It seems to me that we are in agreement on this.
2. Removal of ND. It seems to me that there's worry that we "sign off" on the content, someone takes it and creates derivative that misrepresents the facts while pretending that people have signed/approved of that?

I do not know how do we actually do formal "content signing" here and what happens to it in case of derivative work. I would be surprised if content endorsements can be ported to derivative works but I'm also not a lawyer :-S.

It seems that some of the content authors that chimed in are okay with these kinds of licences, but I would be curious to hear more arguments before proceeding. I got the cc-by licence ready to be merged into master whenever we decide this is what we actually want to do.

**Comment by rousik** [comment]
It seems to me that all derivative works need to be identified as such and link to the original content: https://en.wikipedia.org/wiki/Creative_Commons_license#Attribution

This should, in theory, make it more difficult to intentionally misrepresent the original information, if that is our concern.

**Comment by ShaneCurcuru** [comment]
It depends on the purpose of the site.  If you are trying to be an academic site, then ND may well make sense if you're trying to be like a scientific journal where you quote pages via DOI or whatever.  Personally I don't see how ND really helps with that, but then again I'm an open source developer, not in academia.

If you're trying to be a general public resource site - where you want as many people to learn from your content as possible - then ND is clearly a barrier to **other** groups being able to quote or repurpose your materials.  As an open source person, I'm simply not going to try to paraphrase or copy any of your material when it's under ND.  I may link to it, but that's it.

One advantage to dropping ND is for public communications.  There may well be some great scientific papers here, but they aren't effective at changing social habits, since they're too dense for the average human to bother with. On the other hand, there are a few great "How To Clean Stuff" articles or flyers/handouts that are very simple and straightforward, and can really help public health by getting people to read and follow them.  People writing that kind of materials want to be able to point to research and quote part of it, but they need to be able to write in a way that's simple and easy to follow.

Does that make sense?

**Comment by nditada** [comment]
Quoting a blurb would not constitute a derivative:

> Incorporating an unaltered excerpt from an ND-licensed work into a larger work only creates an adaptation if the larger work can be said to be built upon and derived from the work from which the excerpt was taken. Generally, no derivative work is made of the original from which the excerpt was taken when the excerpt is used to illuminate an idea or provide an example in another larger work.

I understand the concerns nevertheless.  But the issue I describe still stands. I am not talking about an intentional misrepresentation.

In any case, this should be decided by @jmcmurry, @mellybelly and/or @nicolevasilevsky which have already 👍.  @mellybelly @jmcmurry can you confirm that you understand the possible implications of removing the ND when the content is authored and signed by you?

**Comment by rousik** [comment]
I have prepared PR that will switch licence to CC-BY. Please do not approve it until after the consensus is reached here. But once we are confident that CC-BY is what we want, approving that PR should fix this and automatically close this issue as well.

https://github.com/flattenthecurve/guide/pull/358

**Comment by nicolevasilevsky** [comment]
I'm okay with switching to CC-BY.

**Comment by jmcmurry** [comment]
Yep; let's proceed with CC-BY
