### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#35]
- [ ] Content or resource addition request
- [ ] Typo, grammar, small fix.
- [ ] Dispute scientific claim.
- [ ] Others?

**Comment by simonespa** [comment]
I like that @nditada 

What about:
* Content related
  * Resource change (addition, update, removal)
  * Typo, Grammar error, stylistic update and layout, etc.
* Localisation/Translation
* Legal/Scientific disputes
* Website feature request (new tech, linters, unit testing, etc.)
* Website bugfix
* Others?

**Comment by nicolevasilevsky** [comment]
I can work on this.

@jmcmurry could I get write access to this repo? I can then assign myself to tickets

**Comment by nicolevasilevsky** [comment]
Actually, I need write access to  be able to work on this.

Instructions here (for future reference): https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by simonespa** [comment]
@nicolevasilevsky if you don't get write access you can still raise a PR by
- Forking this repo to your own space
- branch off master on a feature branch
- raise the PR against master on the original repo (the PR will be reflected here)

**Comment by nditada** [comment]
@nicolevasilevsky you should have access for PRs now, or simply paste or link here the templates and we'll set them up.

**Comment by mmuller** [comment]
The following templates are working properly:

![image](https://user-images.githubusercontent.com/518152/76712204-3460c800-66f5-11ea-8d35-2c6d53fe8f0f.png)

I close this issue.
