### ISSUE TITLE
Sync translation content with the reorganized act_and_prepare section

### ISSUE THREAD

**Issue by rousik** [flattenthecurve/guide#368]
PR #336 restructured act_and_prepare section. Our live languages need to be updated to catch up with these changes.

The changes that this PR introduces are:
1. addition of new content strings
2. modification of style in existing markdown sections (simplifies headers)
3. couple of files were renamed which changed Lokalise keys and dissociated these from the existing translations.

**Comment by rousik** [comment]
@emersonthis and @nditada for visibility

**Comment by rousik** [comment]
List of renamed keys:

| Original name | New name |
|--|--|
| lower-your-overall-risk | stay-home |
| stay-connected | avoid-crowds |
| shop-when-at-risk | shop-carefully |
| get-a-flu-buddy | pandemic-pal |

Keys added:

| Key |
|-|
| household-practices |
| how-to-not-get-infected |
| how-to-support-your-community |
| tips-to-reduce-stress          | 
| what-to-do-if-you-get-sick  |

Keys removed:
| Key |
|-|
|do           |
|do-not                                           |
|do-not-attend-non-essential-public-gatherings    |
|do-not-be-careless                               |
|do-not-wait           |
|get-enough-vitamin-D    |
|get-your-flu-shot       |
|pick-your-battles       |
|spread-the-word      |
|stock-up-on-food-and-essentials    |
|work-from-home      |

**Comment by rousik** [comment]
My plan is to:
1. see if the renamed keys can be grouped together (I suspect that I may push the new content into the old keys and then use duplicate finder to link them together. Right now this is not possible because the content also changed when the files were renamed)
2. kick of lokalise translation task for the affected keys and all live languages

**Comment by emersonthis** [comment]
Thank you for sorting this out!

**Comment by rousik** [comment]
Key deduplication doesn't work the way I hoped for so we have to rely on translators to port the old content if they need to or translate from scratch. I may just add the notice about changing keys in case they want to look up the old content.

The lokalise tasks for this are:
https://app.lokalise.com/project/423383895e6b8c4b081a89.98184174/?view=multi&filter=task_102538
https://app.lokalise.com/project/423383895e6b8c4b081a89.98184174/?view=multi&filter=task_102557

Due to me misunderstanding how tasks work on Lokalise, Czech has ended up in a separate task.

**Comment by rousik** [comment]
Czech translation updated.

**Comment by rousik** [comment]
Notes about renamed keys:

## stay-home
Drops the paragraph about US being in the initiation phase and link to CDC (seems okay)

## pandemic-pal
Drops the following snippet from the title:
_make back-up plans for care of children, pets, and those in need of special assistance_

Also drops the following paragraph:
_Those who are already struggling with pre-existing demanding medical conditions may have useful experience to share about preparedness and about how to navigate the kinds of operational challenges the rest of us may be just coming to grips with. Ask them what they need from you, then provide it._

Which makes the next paragraph somewhat out-of-context (references _these contingency plans_ that are no longer defined):
_This is a good opportunity to think about longer term versions of these care contingency plans._

**Comment by rousik** [comment]
I have reviewed diffs in the moving files and they're all trivial (collapsing double headers and removing outdated styling).

**Comment by rousik** [comment]
Suggestion about donating medical equipment is now both in the `donate` section as well as under `do-not-hoard`, might be worth consolidation.

**Comment by rousik** [comment]
Here are links to the files that were removed entirely:
[cancel-all-non-essential-travel](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/06-cancel-all-non-essential-travel.md)
[do-not-attend-non-essential-public-gatherings](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/03-dont/04-do-not-attend-non-essential-public-gatherings.md)
[do-not-be-careless](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/03-dont/11-do-not-be-careless.md)
[do-not-wait](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/03-dont/01-do-not-wait.md)
[get-enough-vitamin-D](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/18-get-enough-vitamin-D.md)
[get-your-flu-shot](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/04-get-your-flu-shot.md)
[pick-your-battles](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/10-pick-your-battles.md)
[spread-the-word](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/99-spread-the-word.md)
[stock-up-on-food-and-essentials](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/07-stock-up-on-food-and-essentials.md)
[work-from-home](https://github.com/flattenthecurve/guide/blob/ec161b2e5b3d2cacb166442f41299d514d849f6e/_sections/act_and_prepare/en/02-do/08-work-from-home.md)

**Comment by emersonthis** [comment]
Thanks Jan!

For posterity, it’s worth noting that some of the items listed above as “removed“ were already covered elsewhere under different items. For example: “DO stay home” + “DONT go to work (or crowded places)”.
