### ISSUE TITLE
What to do links on homepage are not valid anymore

### ISSUE THREAD

**Issue by rousik** [flattenthecurve/guide#386]
http://scrgrb.in/cr9 - do/dont links are not valid for English anymore after act_and_prepare has been restructured.

Note that these links are valid for languages that have not been translated yet.

Ideally, the entire blue caption would be clickable and would bring people to Act and prepare section.

I have checked analytics and majority of people do not go beyond the homepage and I wonder whether making this more clickable might help with that (related to issue #325).

**Comment by emersonthis** [comment]
Looks like the link still works but it has a fragment that no longer exists (#do / #dont). We should probably tweak the language a bit too since we're no longer doing such a strict DO / DON'T format.

**Comment by rousik** [comment]
Right, it's not outright broken but it makes no sense. I will try to think about how to update the language for this.

**Comment by rousik** [comment]
well, nevermind, I saw your PR a bit too late :)
