### ISSUE TITLE
Move the "who to follow" list somewhere else

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#39]
Julie prefers to not be linked directly on twitter, let's move the list linked on who to follow somewhere else, also to enable crowd-curation.

**Comment by jmcmurry** [comment]
+1. Also there are lots of people better qualified to really weigh in on this than I am so let's just rethink the whole section and instead say. "There are many experts in this field and we need some time to compile a list." In the meantime, yes please don't link to my twitter, but linkedin is fine. https://www.linkedin.com/in/mcmurryjulie/ thx

**Comment by mverzilli** [comment]
This was addressed (see #58 for more info)
