### ISSUE TITLE
Better style for section headlines

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#40]
We had a really highlighted style for section titles, but those headlines were also used for the TOC and they were too long. 

We should find a way to keep the former (long) headlines highly visible, without having them show up as the TOC entry. 

https://github.com/flattenthecurve/guide/commit/f8c5d5639091d59154917b7f52f157204017cec5

**Comment by bcardiff** [comment]
Closed by 030e14dd6c5980d2a031a93a4c124567a93dcd0a . For now we are using the long names in both places.

Showing short names in the TOC and navigating to long different titles would be confusing.

**Comment by nditada** [comment]
I think we should re-think this, there has to be a way to have a short entry in the TOC and a longer "headline" in a banner fashion, particurarly for the DOs and DON'Ts

**Comment by bcardiff** [comment]
Ok, reimplemented as follows.

**Short/Long title example:**

```md
{:.only_toc}
## Short title

{:.no_toc}
## Long title
```

**Short/Long do title example:**

```md
{:.only_toc}
## Short title

{:.do.no_toc}
## Long title
```

**Short/Long don't title example:**

```md
{:.only_toc}
## Short title

{:.dont.no_toc}
## Long title
```
