### ISSUE TITLE
Keep the "updated on" updated

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#41]
How should we do this? 

Automatically: easy and failproof but minor non-content updates will update the date.
Manually: more accurate but needs instructions to do so and more error-prone.

**Comment by bcardiff** [comment]
We can automate this from the last commit date in the `_content/:lang:` directory using https://stackoverflow.com/questions/25921757/how-to-get-last-commit-date-inside-a-folder-directory-in-github-repo

**Comment by nditada** [comment]
Perfect, go for it!

**Comment by matiasgarciaisaia** [comment]
I'd expect that date to reflect the latest substantial update on the content instead of showing when did we do the latest SEO-related change. Doesn't that make sense?

**Comment by bcardiff** [comment]
That’s why we can use the latest commit date within each content x language folder.

It’s not 100% accurate, but is pretty near.

**Comment by bcardiff** [comment]
Done in 18e9b4109b1a7a45957256f67ec66a2670e87b68 and 80efa968216cd259b61f0f040623a5cbe8d30452
