### ISSUE TITLE
hreflang header implementation

### ISSUE THREAD

**Issue by seancv** [flattenthecurve/guide#44]
Add hreflang tag to the header on all pages:
```

<link rel="alternate" href="https://www.flattenthecurve.com" hreflang="en-us" />
<link rel="alternate" href="https://www.flattenthecurve.com/es/" hreflang="es" />
<link rel="alternate" hreflang="x-default" 
href="https://www.flattenthecurve.com" />
```

**Comment by matiasgarciaisaia** [comment]
We were only missing the `x-default` link - and it's been added in 06b4ec2aa7c7bced0cf2be941fa058fdc95e09a0 & d4d5c5187ba124110acc28743b102fe82da83f93 👍

**Comment by matiasgarciaisaia** [comment]
(The changes may not be live yet due to CloudFlare's cache)
