### ISSUE TITLE
Canonical Tag Implemented on each page

### ISSUE THREAD

**Issue by seancv** [flattenthecurve/guide#45]
Ensure the canonical tag is implemented properly:
```

<link rel="canonical" href="https://www.flattenthecurve.com" />

&

<link rel="canonical" href="https://www.flattenthecurve.com/es/" />
```

Each canonical tag must match the URL of the page.

**Comment by matiasgarciaisaia** [comment]
Canonical tags are already implemented 👍 

https://github.com/flattenthecurve/guide/blob/1a443b02e8b53eead255bbfab8e54e7aae76b768/es/index.html#L12
