### ISSUE TITLE
Guide for translation workflow

### ISSUE THREAD

**Issue by drlbln** [flattenthecurve/guide#59]
I'd to copy that.

I began translating ftc into German yesterday, I'm stuck with the workflow here, tried to email to hello@flattenthecurve.com with no success and would at least like to provide you the litte 1% done so far.

_Originally posted by @drlbln in https://github.com/flattenthecurve/guide/issues/12#issuecomment-599141350_

**Comment by nditada** [comment]
First cut here: https://github.com/flattenthecurve/guide/wiki/Content-translation
