### ISSUE TITLE
Update ALL CAPS to Sentence case

### ISSUE THREAD

**Issue by monicacecilia** [flattenthecurve/guide#6]
For the headers for each of the Dos and Don'ts
- [ ] ALL CAPPS should be replaced with Sentence Case

It makes it easier to read generally, but especially for people with visual disabilities. And Text-to-Voice software also deals better with Sentence cases (I've been told).

**Comment by jkicillof** [comment]
Sentence case please

**Comment by waj** [comment]
Fixed in df50ec106e83372cb22ec5754b6ab4c6f209d83d
