### ISSUE TITLE
Publishing as a Wiki for Rapid and Easy Contribution

### ISSUE THREAD

**Issue by xloem** [flattenthecurve/guide#61]
If anybody tech-minded would know how to make the site _editable_ like a google doc, this could facilitate a lot of combined effort in providing resources, updates, and aid channels.

I know quality is important, but as Wikipedia shows having a lot of people reviewing instead of a limited channel for contribution can be far more effective when there is a huge base of content.

There are projects like https://ikiwiki.info/ but plugging the content straight into a javascript editor might really produce more cooperative contribution.

**Comment by matiasgarciaisaia** [comment]
I think a wiki was not the idea behind this site. From the start, it was part of the intent to have @jmcmurry & her team review every piece of information that gets posted, to avoid spreading misinformation.

There are tons of wikis out there - it's easy to just set that up. And I guess that may even be useful. But it's not what (I understand) this project is or want to be.

Once again, @jmcmurry's take on this would be the one that counts [for me].

I'd close the issue if my guess is correct.

**Comment by emersonthis** [comment]
Agreed. I recommend closing this.

**Comment by xloem** [comment]
Okay.  Mostly I bring it up because I couldn't find any central resource for community supports to organize (things like makerspace ventilator designs, money pools to facilitate self-quarantining, everyone has new ideas and new work to help) and you guys seem to have both legitimate centralization and some technological resources to make a website.

**Comment by matiasgarciaisaia** [comment]
I guess we may want to link to some nice wiki from the Who to follow/How to contribute sections, but we're not aiming at creating that wiki/community ourselves.

I'll close the issue, but please feel free to make a pull request with a link if you find such community 👍

**Comment by matiasgarciaisaia** [comment]
BTW: thanks for the intention, @xloem!
