### ISSUE TITLE
Current build has rendering issues on mobile and the link section is now at the bottom of the document 

### ISSUE THREAD

**Issue by andreimoment** [flattenthecurve/guide#66]
Both of these are on mobile (iPhone 8 iOS 13)

### 1. Rendering issues: 

Content stretches wider than the background. See screenshot below. 

 
![B4414E9D-EF13-416B-B10C-4871C8232E8C](https://user-images.githubusercontent.com/6190/76693548-4f173c00-6624-11ea-9980-ef7b1e76bdb0.png)

### 2. Navigation Links are no longer available at the beginning of the document. 

They now appear at the end of the document. 

This IMO is a usability regression because it removes the table of contents from immediate view. Please consider reverting.

The TOC is very well written and when posted at the top, makes the document easy to navigate.

**Comment by bcardiff** [comment]
This is fixed now.
