### ISSUE TITLE
Shorten Spanish titles for ToC readibility

### ISSUE THREAD

**Issue by matiasgarciaisaia** [flattenthecurve/guide#67]
Titles in Spanish still have the old, long versions. We should trim them to improve the ToC's readibility.

**Comment by bcardiff** [comment]
On hold until #40

**Comment by bcardiff** [comment]
No longer needed. Back to long titles.

**Comment by bcardiff** [comment]
Ok, this is needed again. Check https://github.com/flattenthecurve/guide/issues/40#issuecomment-599513474 for appropieate format.

**Comment by nditada** [comment]
Done!
