### ISSUE TITLE
[Translation] Italian translation needed

### ISSUE THREAD

**Issue by simonespa** [flattenthecurve/guide#73]
I'm volunteering to translate this document in Italian. but of course I don't have domain knowledge. Help needed for proof reading and image translations as well.

**Comment by simonespa** [comment]
I forked this repo on my personal one and started with a first iteration of the translation. I will be opening a draft PR soon.

**Comment by mverzilli** [comment]
Hi @simonespa there is now an Italian version the site. Head to https://github.com/flattenthecurve/guide/wiki/Content-translation if you want to contribute to keeping it up to date with the English version. Thank you!
