### ISSUE TITLE
Do: Travel -- confusing "at a glance"

### ISSUE THREAD

**Issue by seancv** [flattenthecurve/guide#78]
Got an email pointing out that if you scan the ToC it basically says Do: Travel.

But under "Travel" it says "cancel all travel. 

Can we update the heading (on the green background and on the ToC) to be:

Cancel Travel?

Just so it's clear at a glance that's what we mean :)

**Comment by emersonthis** [comment]
I just submitted [PR #82](https://github.com/flattenthecurve/guide/pull/82) which fixes this.

**Comment by mmuller** [comment]
![image](https://user-images.githubusercontent.com/518152/76760204-fce13280-676b-11ea-820a-35801f46cfd8.png)
