### ISSUE TITLE
Convert pictures to text

### ISSUE THREAD

**Issue by jkicillof** [flattenthecurve/guide#8]
For a11y purposes, all text images with no charts will be converted to text and styled with css. 

Image examples:
![image](https://user-images.githubusercontent.com/5031636/76649656-e6569380-653f-11ea-9878-82c9969a38fc.png)
![image](https://user-images.githubusercontent.com/5031636/76649687-f2daec00-653f-11ea-85b9-328a02187ecd.png)
![image](https://user-images.githubusercontent.com/5031636/76649709-fec6ae00-653f-11ea-83b0-81362be6109d.png)

**Comment by danimiba** [comment]
### First image:

> Frustrated by the lack of testing resulting from the problem with the CDC-developed kit, the Seattle Flu Study began using an in-house developed test to look for Covid-19 in samples from people who had tested negative for flu. That work —permissible because it was research— uncovered the Snohomish County teenager.

### Second image:

> What’s your risk of inadvertently allowing the death of someone in your community from COVID-19?
> 	* A local school district shifting to online learning will save 10 lives every week.
> 	* A 100,000 person conference canceled saves 200 lives.
> 	* If you and 20 coworkers _work from home_ for 4 days, that action on average will save one life over the next two months.
> 	* _Staying home when sick_ with #COVID19 prevents you from transmitting to 2-3 other people and causing 100 others to get it, of whom 15-20 are likely to be hospitalized and 1 is likely to die.
> 
> _by @ScottLeibrand and @DanaMLewis, see http://bit.ly/COVID19communityimpact_

**Comment by scottleibrand** [comment]
Are you looking to add alt-text to the images for accessibility, or completely switch them over to text only?

**Comment by danimiba** [comment]
I would think that to be able to translate this we need them in text only, and style them with css
@nditada @jkicillof do you agree?

**Comment by emersonthis** [comment]
I can do this later today... should my PR replace the images on the English homepage only? And then someone will latter add the translations to the other languages? I’m still figuring out how issues like these fit into the translation workflow. @nditada

**Comment by tpltnt** [comment]
addressed in part in #125

**Comment by nditada** [comment]
@nditada correct. YOu only worry about the english version, then new translation keys go to Lokalise and translation teams translate the new content
