### ISSUE TITLE
Broken link in Spanish version

### ISSUE THREAD

**Issue by mmuller** [flattenthecurve/guide#87]
**Bug:**
Broken link: `https://www.flattenthecurve.com/es/es`

**Suggested fix:**
`Replace https://www.flattenthecurve.com/es/es` with `https://www.flattenthecurve.com/es`

Screenshot:

![image](https://user-images.githubusercontent.com/518152/76712010-7db01800-66f3-11ea-8943-9825b8bf8da9.png)

**Comment by matiasgarciaisaia** [comment]
We need to update the Lokalise entry with the link like this: `[www.flattenthecurve.com/es](https://www.flattenthecurve.com/{{site.active_lang}}/)`. Jekyll (the site generator) is parsing the link, and it won't work otherwise.
