### ISSUE TITLE
Y axis mislabeled

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#88]
Please report the issue under the apppriate header below.

**Content to be added or changed:**

"Hi Ms. McMurry,
Excellent job pulling the info together, but there’s a glaring error us math types see. The y axis is labeled incorrectly on your website. The y axis is number of cases per unit of time. The area under the curve is the total number of cases. In other words, we’re trying to pace out the cases, not claiming to reduce the total number of cases.
Please correct! 
Thank you,
[redacted]
"

**Comment by rousik** [comment]
This issue should be no longer relevant because the picture in question is no longer shown.
