### ISSUE TITLE
Fix Titles for Don'ts and Julie's Bio

### ISSUE THREAD

**Issue by monicacecilia** [flattenthecurve/guide#9]
- [x] Fix color for background and text: starting with the title "DO NOT SHAKE HANDS..." the red background and white font are gone. 
- [x] Fix Title for Julie's bio "About the author:" header is not correctly configured and has an additional curly bracket.

**Comment by monicacecilia** [comment]
Fixed. You can close.

**Comment by monicacecilia** [comment]
Ack! sorry. Julie's Bio still needs to be fixed.

**Comment by danimiba** [comment]
Hi @monicacecilia, could you please take a screenshot of the issue? I can't seem to find it

**Comment by nditada** [comment]
Here @danimiba: 
<img width="1148" alt="Screen Shot 2020-03-13 at 6 43 59 PM" src="https://user-images.githubusercontent.com/1359189/76661625-a650da00-655a-11ea-9e99-377b76e30a0b.png">

**Comment by monicacecilia** [comment]
Dear @danimiba - I see that this is fixed. Thanks!

**Comment by monicacecilia** [comment]
Requested fix for header in Julie's bio in #33
