### ISSUE TITLE
add "close toilet seat before flushing"

### ISSUE THREAD

**Issue by jmcmurry** [flattenthecurve/guide#91]
**Content to be added or changed:**
Risks may be negligible, but easy to do. Some fecal oral transmission reported; data not solid yet.

**Comment by cmcnamara87** [comment]
https://en.wikipedia.org/wiki/Toilet_plume

**Comment by mverzilli** [comment]
This was discussed and discarded in https://github.com/flattenthecurve/guide/pull/140
