### ISSUE TITLE
[English] "About" pages appear under the "Don't" heading in the navigation on the left

### ISSUE THREAD

**Issue by emersonthis** [flattenthecurve/guide#92]
**Bug:**
Currently there are several page links that appear under the "Don't" heading in the navigation links on the left. This is confusing.
<img width="1654" alt="Screen Shot 2020-03-15 at 7 07 39 PM" src="https://user-images.githubusercontent.com/1728139/76717402-78050300-66f0-11ea-8784-614b2fdbc969.png">

**Suggested fix:**
Create a new "About" heading for those last few links that don't belong under "Don't"

**Comment by mmuller** [comment]
It only happens when using the English version.

Spanish version:

![image](https://user-images.githubusercontent.com/518152/76717784-6ed95d80-6713-11ea-8e6d-83f0b5589e3b.png)

**Comment by emersonthis** [comment]
Thanks! That's helpful. I'm reading up on the [jekyll-toc](https://github.com/toshimaru/jekyll-toc) plugin which appears to be powering that...

**Comment by bcardiff** [comment]
Fixed in 030e14dd6c5980d2a031a93a4c124567a93dcd0a
