### ISSUE TITLE
Bleach to water ratio from CDC

### ISSUE THREAD

**Issue by nditada** [flattenthecurve/guide#97]
**Content to be added or changed:**

source: https://www.cdc.gov/coronavirus/2019-ncov/community/home/cleaning-disinfection.html

Clean and disinfect
Clean AND disinfect frequently touched surfaces daily. This includes tables, doorknobs, light switches, countertops, handles, desks, phones, keyboards, toilets, faucets, and sinks.
If surfaces are dirty, clean them: Use detergent or soap and water prior to disinfection.
To make a bleach solution, mix:
5 tablespoons (1/3rd cup) bleach per gallon of water
OR
4 teaspoons bleach per quart of water

Home cleaning and disinfection Recommendations:

**Comment by rousik** [comment]
https://github.com/flattenthecurve/guide/pull/249 for this
